micronaut:
  server:
    port: 18085
    cors:
      enabled: true
  application:
    name: notary-api
---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
---
# https://docs.micronaut.io/latest/guide/index.html#jsonBinding
jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false
