apiVersion: v1
kind: Service
metadata:
  name: notary-api
  labels:
    app: notary-api
spec:
  ports:
  - port: 8085
    name: http
  selector:
    app: notary-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notary-api
  labels:
    app: notary-api
spec:
  selector:
    matchLabels:
      app: notary-api
  replicas: 1
  template:
    metadata:
      labels:
        app: notary-api
    spec:
      containers:
      - name: notary-api
        image: notary/api:local
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 18085
